name: 18-working with-matrices

on:
 workflow_dispatch:


jobs:
  backward-compatibility:
    runs-on: ${{ matrix.os }}-${{ matrix.node-version }}
    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]
        os: [ubuntu-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}

      - name: Show environment
        run: |
          echo "Running on OS: ${{ matrix.os }}"
          node -v
          npm -v