name: 20.1-Reusable Workflows - Reusable Definition

on:
  workflow_call:
    inputs:
      target-directory:
        description: 'The target directory to deploy'
        required: true
        type: string
    outputs:
      build-status:
        description: 'The build status'
        value: ${{ jobs.deploy.outputs.build-status }}
      url:
        description: 'The deployment URL'
        value: ${{ jobs.deploy.outputs.url }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    outputs:
      build-status: ${{ steps.build.outputs.build-status }}
      url: ${{ steps.deploy.outputs.url }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Build
        id: build
        run: |
          echo "Building the project using directory ${{ inputs.target-directory }} ..."
          echo "build-status=success" >> "$GITHUB_OUTPUT"

      - name: Deploy
        id: deploy
        run: |
          echo "Deploying build artifacts..."
          echo "url=http://www.google.com" >> "$GITHUB_OUTPUT"
